apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
  namespace: dev
  labels:
    app: mywebapp
spec:
  ports:
    - port: 80
      protocol: TCP
      name: nginxapplication
  selector:
    app: mywebapp
    tier: frontend
  type: NodePort
  
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
  namespace: prod
  labels:
    app: mywebapp
spec:
  ports:
    - port: 80
      protocol: TCP
      name: nginxapplication
  selector:
    app: mywebapp
    tier: frontend
  type: NodePort