apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: dev
  labels:
    app: mywebapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "125Mi"
            cpu: "100m"
        volumeMounts:
          - name: nginx-config
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-configv2
            items:
              - key: index.html
                path: index.html